"""Scale memo and prompt search indexes.

Revision ID: 20260710_01
Revises: 20260709_01
Create Date: 2026-07-10
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260710_01"
down_revision: Union[str, Sequence[str], None] = "20260709_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add search indexes and move semantic ranking to pgvector."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(
        """
        ALTER TABLE memo_entries
        ADD COLUMN IF NOT EXISTS embedding_vector vector(768)
        """
    )

    # Existing embeddings are JSON arrays generated by the same 768-dimensional model.
    # Invalid legacy values are ignored so the migration remains deployable; subsequent
    # memo updates regenerate their embedding through the normal background job.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION try_memo_embedding_vector(raw_embedding TEXT)
        RETURNS vector
        LANGUAGE plpgsql
        IMMUTABLE
        AS $$
        DECLARE
            parsed_embedding vector;
        BEGIN
            parsed_embedding := raw_embedding::vector;
            IF vector_dims(parsed_embedding) <> 768 THEN
                RETURN NULL;
            END IF;
            RETURN parsed_embedding;
        EXCEPTION WHEN OTHERS THEN
            RETURN NULL;
        END;
        $$
        """
    )
    op.execute(
        """
        UPDATE memo_entries
           SET embedding_vector = try_memo_embedding_vector(embedding)
         WHERE embedding_vector IS NULL
           AND embedding IS NOT NULL
        """
    )
    op.execute("DROP FUNCTION IF EXISTS try_memo_embedding_vector(TEXT)")

    # Build the large indexes without holding a write lock for their full duration.
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_memo_entries_title_trgm
                ON memo_entries USING gin (title gin_trgm_ops)
            """
        )
        op.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_memo_entries_response_trgm
                ON memo_entries USING gin (ai_response gin_trgm_ops)
            """
        )
        op.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_memo_entries_embedding_vector_hnsw
                ON memo_entries USING hnsw (embedding_vector vector_cosine_ops)
                WHERE embedding_vector IS NOT NULL
            """
        )
        op.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_username_trgm
                ON users USING gin (username gin_trgm_ops)
            """
        )


def downgrade() -> None:
    """Remove the search indexes and pgvector column."""
    with op.get_context().autocommit_block():
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS idx_users_username_trgm")
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS idx_memo_entries_embedding_vector_hnsw")
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS idx_memo_entries_response_trgm")
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS idx_memo_entries_title_trgm")

    op.execute("ALTER TABLE memo_entries DROP COLUMN IF EXISTS embedding_vector")
