from __future__ import annotations

MEMO_NOT_FOUND_ERROR = "メモが見つかりません。"
COLLECTION_NOT_FOUND_ERROR = "コレクションが見つかりません。"
DEFAULT_MEMO_LIST_LIMIT = 20
MAX_MEMO_LIST_LIMIT = 100
DEFAULT_EXCERPT_LENGTH = 180
SEMANTIC_SEARCH_MAX_MEMOS = 500
