import type { MemoPageControllerState } from "../contexts/memo_page/memo_page_context";

// テスト用の controller スタブ。全キーを不活性なデフォルトで埋め、必要なものだけ上書きする。
// 完全な型で書いているので、controller のキーが増減・改名されると typecheck が落ちる（意図した契約）。
// Controller stub for tests: every key gets an inert default and tests override what they need.
// It is typed as the full controller state on purpose, so any key change in the controller
// fails `npm run typecheck` here.
const noop = () => undefined;
const asyncNoop = async () => undefined;
const asyncFalse = async () => false;

export const memoPageControllerStubDefaults: MemoPageControllerState = {
  // auth
  isLoggedIn: false,
  authUiReady: true,
  // flash
  flashState: null,
  setFlashState: noop,
  showFlash: noop,
  // layout
  activeView: "memos",
  setActiveView: noop,
  viewMode: "grid",
  setViewMode: noop,
  isFiltersOpen: false,
  setIsFiltersOpen: noop,
  isSidebarCollapsed: false,
  setIsSidebarCollapsed: noop,
  // list
  query: "",
  setQuery: noop,
  sortMode: "manual",
  setSortMode: noop,
  archiveScope: "active",
  setArchiveScope: noop,
  activeCollectionId: null,
  setActiveCollectionId: noop,
  memos: [],
  totalMemoCount: 0,
  memoLoadError: undefined,
  memoListLoading: false,
  mutate: asyncNoop,
  updateMemoListOptimistically: asyncNoop,
  hasActiveFilters: false,
  // collections
  collections: [],
  mutateCollections: asyncNoop,
  activeCollection: null,
  isCollectionPanelOpen: false,
  setIsCollectionPanelOpen: noop,
  newCollectionName: "",
  setNewCollectionName: noop,
  newCollectionColor: "#6b7280",
  setNewCollectionColor: noop,
  collectionActionLoading: false,
  editingCollectionId: null,
  setEditingCollectionId: noop,
  editingCollectionName: "",
  setEditingCollectionName: noop,
  editingCollectionColor: "#6b7280",
  setEditingCollectionColor: noop,
  handleCreateCollection: asyncNoop,
  handleUpdateCollection: asyncNoop,
  handleDeleteCollection: asyncNoop,
  // composer
  formState: { ai_response: "", title: "", collection_id: null, background_color: null },
  setFormState: noop,
  previewMode: false,
  setPreviewMode: noop,
  submitting: false,
  aiSuggesting: false,
  isComposePaletteOpen: false,
  setIsComposePaletteOpen: noop,
  setIsComposeExpanded: noop,
  composeTextareaRef: { current: null },
  handleFormChange: noop,
  handleSubmitMemo: asyncNoop,
  handleAiSuggest: asyncNoop,
  openTextComposer: noop,
  openChecklistComposer: noop,
  openComposePalette: noop,
  hasComposeDraft: false,
  composeIsExpanded: false,
  // detail
  selectedMemo: null,
  isMemoDetailClosing: false,
  detailLoading: false,
  detailError: "",
  detailPreviewMode: true,
  setDetailPreviewMode: noop,
  detailEditTitle: "",
  setDetailEditTitle: noop,
  detailEditCollectionId: null,
  setDetailEditCollectionId: noop,
  detailEditAiResponse: "",
  setDetailEditAiResponse: noop,
  detailEditBackgroundColor: null,
  setDetailEditBackgroundColor: noop,
  detailSaveStatus: "idle",
  detailSaveError: "",
  isMemoAgentOpen: false,
  setIsMemoAgentOpen: noop,
  detailHasUnsavedChanges: false,
  openMemoDetail: asyncNoop,
  closeMemoDetail: asyncNoop,
  openMemoAgent: asyncNoop,
  saveDetailEdit: async () => true,
  copyDetailFullText: asyncFalse,
  patchSelectedMemoOptimistically: noop,
  refreshSelectedMemoIfNeeded: asyncNoop,
  startMemoDetailCloseAnimation: noop,
  // action menu
  openMenuMemoId: "",
  setOpenMenuMemoId: noop,
  menuPosition: null,
  setMenuPosition: noop,
  closeMemoActionMenu: noop,
  toggleMemoActionMenu: noop,
  // bulk
  isBulkMode: false,
  setIsBulkMode: noop,
  selectedIds: new Set<string>(),
  bulkCollectionId: null,
  setBulkCollectionId: noop,
  bulkLoading: false,
  hasSelection: false,
  toggleSelectMemo: noop,
  selectAll: noop,
  deselectAll: noop,
  executeBulkAction: asyncNoop,
  exitBulkMode: noop,
  // drag
  canDragMemos: false,
  canReorderCurrentView: false,
  draggedMemoId: "",
  cardRefs: { current: new Map<string, HTMLElement>() },
  displayMemos: [],
  pinnedMemos: [],
  otherMemos: [],
  clearMemoDragState: noop,
  handleMemoDragStart: noop,
  handleMemoSectionDragOver: noop,
  handleMemoDrop: asyncNoop,
  // item actions
  actionLoadingId: "",
  copyingMemoId: "",
  handleTogglePin: asyncNoop,
  handleToggleArchive: asyncNoop,
  handleDeleteMemo: asyncNoop,
  copyMemoFullText: asyncFalse,
  // share
  isShareModalOpen: false,
  setIsShareModalOpen: noop,
  shareUrl: "",
  shareStatus: null,
  shareLoading: false,
  supportsNativeShare: false,
  shareSnsLinks: { x: "", line: "", facebook: "" },
  openShareModal: asyncNoop,
  closeShareModal: noop,
  copyShareLink: asyncFalse,
  openNativeShareSheet: asyncNoop,
  // export
  isExportModalOpen: false,
  setIsExportModalOpen: noop,
  exportFormat: "markdown",
  setExportFormat: noop,
  exportScope: "all",
  setExportScope: noop,
  exportSelectedIds: new Set<string>(),
  exportSelectedCount: 0,
  allVisibleExportSelected: false,
  canDownloadExport: true,
  toggleExportMemo: noop,
  selectAllExportMemos: noop,
  clearExportSelection: noop,
  handleExport: noop,
};

export function createMemoPageControllerStub(
  overrides: Partial<MemoPageControllerState> = {},
): MemoPageControllerState {
  return { ...memoPageControllerStubDefaults, ...overrides };
}
